Feature/wnb 89/api request middleware
Wannabook/wannabook-frontend pull request #5
Opened 2019-04-12 15:59 UTC by DmitriLipski

2019-04-12 20:31 UTC, ikushlianski requested changes

2019-04-12 20:31 UTC, ikushlianski commented on src/components/OrganizationsList/Component.js
> +  renderError = error => {
Would be nice to separate expressions with a blank line

2019-04-12 20:31 UTC, ikushlianski commented on src/mockApi/ApiClient.js
> +  get(resourceUrl) {
let's also separate methods with blank line

2019-04-12 20:31 UTC, ikushlianski commented on src/routes/Page1.js
>  import './style.scss';
Let's order our imports here

2019-04-12 20:31 UTC, ikushlianski commented on src/store/modules/organizations/constants.js
>  export const INITIAL_STATE = {
Could we abstract away this INITIAL_STATE since it's common for all entities in our app, not only organizations?

2019-04-12 20:31 UTC, ikushlianski commented on src/components/OrganizationsList/index.js
> +export function mapDispatchToProps(dispatch) {
Why exporting this function?

2019-04-12 20:31 UTC, ikushlianski commented on src/components/OrganizationsList/index.js
> +const mapStateToProps = () => {
You write one function as arrow function and the other (mapDispatchToProps) as a usual function.

Let's maybe do everything in arrow style?

2019-04-12 20:31 UTC, ikushlianski commented on src/components/OrganizationsList/index.js
> +  return globalState => {
We could do an implicit return here like 

```
const mstp = () => globalState => ({
    ...getOrganizationsLoadingProps(globalState),
    organization: getOrganizations(globalState),
})
```

2019-04-12 20:31 UTC, ikushlianski commented on src/components/OrganizationsList/index.js
> +      organization: getOrganizations(globalState),
Shouldn't the prop be `organizations`?

2019-04-12 20:31 UTC, ikushlianski commented on src/components/OrganizationsList/Component.js
> +              return (
We could remove an extra return here

2019-04-12 20:31 UTC, ikushlianski commented on src/components/OrganizationsList/index.js
> +export default connect(
Let's discuss the usage of default exports during weekly call

2019-04-12 20:31 UTC, ikushlianski commented on src/components/OrganizationsList/Component.js
> +    return <h3>Loading...</h3>;
Extra returns could be removed here and above to save some lines of code)

2019-04-12 20:31 UTC, ikushlianski commented on src/components/OrganizationsList/index.js
> +)(Component);
I would put `mstp` and `mdtp`  to the same page where we write our component, so that we clearly see what props come from where.

2019-04-12 20:31 UTC, ikushlianski commented on src/store/modules/organizations/reducer.js
> +    loading: true,
we should add `loaded: false`

2019-04-14 07:48 UTC, DmitriLipski commented on src/store/modules/organizations/constants.js
>  export const INITIAL_STATE = {
It's inital state only for "organization" key

2019-04-14 13:23 UTC, ikushlianski approved these changes

2019-04-14 13:23 UTC, merged